add support for SRV records (python)
FragLand/minestat pull request #152
Opened 2023-02-03 11:01 UTC by Sch8ill

## Proposed Changes (python)
- add support for SRV records
- bump version to 2.5.0
- add dnspython as dependency in pyproject.toml
- mark this package as statically type (PEP-0561)
- fix small bug from prior pull request

I'm so sorry for the extra effort
I think it would be best if the pull request would be squashed because of the many commits.

2023-02-03 20:11 UTC, mindsolve requested changes
Hi @Sch8ill,

Thank you very much for the contribution!
Sorry that I have so many comments 😉 - please do not be discouraged to further submit changes!

The two major points:
- There is [no support for SRV records in Minecraft Bedrock](https://feedback.minecraft.net/hc/en-us/community/posts/360016429012-SRV-Record-Support-Bedrock-Edition-), so all logic regarding that diverges from the actual way the client resolves the server address and is not needed.
- You can replace your "is IP address" check with the system module `ipaddress`

After that's changed, looks good!

Best regards,
MindSolve

2023-02-03 20:11 UTC, mindsolve commented on Python/minestat/__init__.py
> +        port = self._resolve_srv_record(self.address, proto="udp")
There is currently no support for SRV records in Minecraft Bedrock: https://feedback.minecraft.net/hc/en-us/community/posts/360016429012-SRV-Record-Support-Bedrock-Edition-

2023-02-03 23:53 UTC, Sch8ill commented
All problems are resolved.
i'm very sorry for this mess, this pull request really needs to be squashed.

2023-02-04 18:28 UTC, mindsolve approved these changes
Looks good :)

2023-02-04 18:28 UTC, merged