add support for the Query / GamSpot4 / UT3 protocol (python)
FragLand/minestat pull request #166
Opened 2023-02-09 19:50 UTC by Sch8ill

## Proposed Changes
- add support for the Query / GamSpot4 / UT3 protocol

New values: minestat.player_list, minestat.plugins and minestat.map.

The basic stat request of the Query protocol isn't implemented yet (isn't necessary in my opinion, because the only difference is that you get less data).

There is currently no latency measuring for the Query protocol implemented.

The Query protocol isn't included in the "all protocols" option.

2023-02-10 00:47 UTC, ldilley commented
Related to #143.

2023-02-11 00:34 UTC, mindsolve requested changes
Hi @Sch8ill,

Thank you for the PR! This looks great, even if I added lots of comments. I particlularly like your code fitting perfectly in the style of the rest of the code :)

Best regards,
MindSolve

2023-02-11 00:34 UTC, mindsolve commented on Python/minestat/__init__.py
> +      challenge_token_bytes = struct.pack('>l', int(challenge_token[:-1]))
The geyser server software seems to send two NUL bytes at the end of the handshake response? Using rstrip on the challenge_token fixes this, ignoring as many NULs as the server throws at us :D

```suggestion
      challenge_token = handshake_res[5:].rstrip(b'\00')

      # pack the challenge token into a big-endian long (int32)
      challenge_token_bytes = struct.pack('>l', int(challenge_token))
```

Error message running your branch against a geyser server:
```
  File "C:\Users\username\Programmieren\Python\minestat-demo\example.py", line 5, in <module>
    ms = minestat.MineStat('193.135.10.3', 15224, query_protocol=minestat.SlpProtocols.Query)
  File "C:\Users\username\Programmieren\Python\minestat-demo\venv\lib\site-packages\minestat\__init__.py", line 273, in __init__
    result = self.fullstat_query()
  File "C:\Users\username\Programmieren\Python\minestat-demo\venv\lib\site-packages\minestat\__init__.py", line 574, in fullstat_query
    challenge_token_bytes = struct.pack('>l', int(challenge_token[:-1]))
ValueError: invalid literal for int() with base 10: b'-599651295\x00'
```

2023-02-11 00:34 UTC, mindsolve commented on Python/minestat/__init__.py
> +      # the list conatins the key to the value and the value right in the element behind it
```suggestion
      # the list contains the key to the value and the value right in the element behind it
```

2023-02-11 00:34 UTC, mindsolve commented on Python/minestat/__init__.py
> +        # the plugins are seperated by " ;"
```suggestion
        # the plugins are separated by " ;"
```

2023-02-11 00:34 UTC, mindsolve commented on Python/minestat/__init__.py
> +  Query = 6
Could you please use UPPER_CASE_SNAKE_CASE, like the other keys?

2023-02-13 12:48 UTC, Sch8ill commented on Python/minestat/__init__.py
> +          stat_values.append(element)
oops, didn't thought about that🙃. That seems like a good idea, I'm definitly going to change this.

2023-02-13 17:34 UTC, Sch8ill commented on Python/minestat/__init__.py
> +          self.version, self.plugins[0] = self.plugins[0].split(": ")
@mindsolve That's a tricky question, I think it's ok to keep it the way it is for now.
I would guess the only way to solve is to do some checking with a regex.
I don't know how this is implemented on other servers though.

2023-02-19 15:09 UTC, ldilley approved these changes

2023-02-19 15:13 UTC, ldilley commented on Python/minestat/__init__.py
> +    session_id_int = random.randint(0, 2147483648) & 0x0F0F0F0F
@sonatype-lift ignore

The data contained in this traffic is not sensitive.

2023-02-19 16:56 UTC, merged