fixed [FragLand#216](FragLand#216) for javascript, PHP and Python
FragLand/minestat pull request #217
Opened 2024-03-16 00:21 UTC by molanp

fixed [FragLand#216](FragLand#216) for javascript, PHP and Python

2024-03-21 03:48 UTC, ldilley reviewed
Greetings, @molanp.

In reference to issue #216, only data returned from SLP 1.7 JSON queries is potentially impacted, correct? If this is the case, then the JavaScript changes in this PR are unnecessary considering that the JavaScript implementation only supports SLP 1.4/1.5. Furthermore, the included PHP modifications would not correct the issue for SLP 1.7. The changes would need to be made to the following lines (613 and 614) in `minestat.php`:
```php
      $this->current_players = (int)@$json_data['players']['online'];
      $this->max_players = (int)@$json_data['players']['max'];
```

Tagging @mindsolve to see if he has any input for the proposed Python changes.

2024-03-23 17:21 UTC, mindsolve requested changes
Thanks for the ping, ldilley :)

I just have one small comment for the python edition.
Thank you, @molanp for the contribution!

2024-03-23 17:21 UTC, mindsolve commented on Python/minestat/__init__.py
> +      self.player_list = [player["name"] for player in players["sample"]]
I think this only works if the whole "players" object is missing. If either the "max" or "online" properties are missing but the players element exists, it is still going to raise an exception here. I would prefer if that would also be cought.

2024-03-29 11:08 UTC, molanp commented
Done.

2024-03-30 19:09 UTC, mindsolve approved these changes
In regards to the Python parts: Approved, thanks for the addition!

2024-03-30 19:36 UTC, ldilley approved these changes
The JavaScript and PHP changes now look good as well. Thank you for the fixes, @molanp!

2024-03-30 19:37 UTC, merged